org: asudre
app: tech-watch-cron
component: aws-lambda-cron

name: aws-lambda-cron-template

author: Aaron Stuyvenberg
inputs:
  src: ./src/
  schedule: cron(0 * * * ? *)
  env:
    webhookUrl: https://izmaz8n31d.execute-api.us-east-1.amazonaws.com/webhook

    # Api key
    apiKey: ${env:API_KEY}