service: tech-watch

provider:
  name: aws
  runtime: nodejs14.x
  region: 'eu-west-1'
  frameworkVersion: '>=1.43.0'

plugins:
  - serverless-dotenv-plugin

functions:
  cron-feed-trello:
    timeout: 60
    handler: src/index.handler
    events:
      - schedule: rate(${env:RATE_IN_HOURS} hours)
